[package]
name = "congruencer"
version = "0.1.0"
authors = ["Alexey Pryanichnikov <genary@ya.ru>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
itertools = "0.12.1"

[dependencies]
rayon = "1.5.3"
